version: '3.9'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-postgres.properties
    image: mustafasdocker1/conductor-server:v3.13.2
    networks:
      - internal
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - elasticsearch:es
      - postgres:postgresdb
    depends_on:
      elasticsearch:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080
    image: mustafasdocker1/conductor-ui:v3.13.2
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server
    stdin_open: true

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=conductor
      - POSTGRES_PASSWORD=conductor
    volumes:
      - pgdata-conductor:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - 5432:5432
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  elasticsearch:
    platform: linux/amd64
    image: elasticsearch:6.8.15
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 10s
      timeout: 5s
      retries: 50
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  workers-app:
    depends_on:
      conductor-server:
        condition: service_healthy
    build: ../workers
    restart: on-failure
    networks:
      - internal
    ports:
      - 8082:8082
    stdin_open: true
    tty: true

volumes:
  pgdata-conductor:
    driver: local
  esdata-conductor:
    driver: local

networks:
  internal:
